name: .NET

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:latest  # Use the latest version of Neo4j
        ports:
          - 7687:7687

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore RestNeo4j/RestNeo4j.csproj

      - name: Build
        run: dotnet build --no-restore RestNeo4j/RestNeo4j.csproj

      - name: Test
        run: dotnet test --no-build --verbosity normal RestNeo4j/RestNeo4j.csproj
